[project]
name = "jyablonski-nba-elt-airflow"
version = "2.2.8"
description = "Practice Apache Airflow Repo"
authors = [{ name = "jyablonski9", email = "jyablonski9@gmail.com" }]
requires-python = "==3.12.*"
readme = "README.md"
dependencies = [
    "apache-airflow-providers-amazon>=8.29.0,<9",
    "apache-airflow-providers-discord>=3.8.0,<4",
    "apache-airflow-providers-postgres>=5.13.0,<6",
    "apache-airflow-providers-slack>=8.9.0,<9",
    "apache-airflow-providers-pagerduty>=3.8.0,<4",
    "apache-airflow-providers-snowflake>=5.7.1,<6",
    "awswrangler>=3.9.1,<4",
    "moto>=5.0.16,<6",
    "airflow-parse-bench>=1.0.1,<2",
]

[dependency-groups]
dev = [
    "pytest>=7.4.4,<8",
    "black>=23.12.1,<24",
    "ruff>=0.1.14,<0.2",
    "mypy>=1.8.0,<2",
    "ipykernel>=6.29.0,<7",
]

[tool.uv]
package = false

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
