version: 2

sources:
  - name: nba_airflow
    database: jacob_db
    description: Landing Zone for NBA Source Data
    tables:
      - name: aws_stats_source
        description: Raw player aggregate stats
      - name: aws_injury_data_source
        description: Raw player injury data
        columns:
          - name: player
            tests:
              - not_null
          - name: team
            tests:
              - not_null
          - name: description
            tests:
              - not_null
      - name: aws_transactions_source
        description: Raw player & team trades + transactions
        columns:
          - name: date
            tests:
              - not_null
          - name: transaction
            tests:
              - not_null
      - name: aws_adv_stats_source
        description: Raw team advanced stats
        columns:
          - name: team
            tests:
              - not_null
      - name: aws_reddit_data_source
        description: Raw reddit data 
        loaded_at_field: scrape_time
        freshness:
          warn_after: {count: 480, period: hour}
          error_after: {count: 720, period: hour}
        loaded_at_field: datetime1
        freshness:
          warn_after: {count: 700, period: hour}
          error_after: {count: 1400, period: hour}
      - name: aws_contracts_source
        description: Raw contracts table
      - name: aws_pbp_data_source
        description: Raw pbp table