
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'nba_elt_project_airflow'
version: '1.0.0'
config-version: 2

vars:
  'dbt_date:time_zone': 'America/Chicago'

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  nba_elt_project_airflow:
      # Applies to all files under models/example/
      marts:
        +materialized: table
        +schema: nba_prod_airflow
        +tags:
          - "NBA_AIRFLOW_MARTS"
      prep:
        +materialized: view
        +schema: nba_prod_airflow
        +tags:
          - "NBA_AIRFLOW_PREP"
      staging:
        +materialized: view
        +schema: nba_staging_airflow
        +tags:
          - "NBA_AIRFLOW_STAGING"
seeds:
  nba_elt_project:
    +schema: nba_staging_airflow
    +tags:
      - "NBA_AIRFLOW_STAGING"
