use database production;
use role accountadmin;


create database development clone production;

-- Step 1: Revoke all privileges on the DEVELOPMENT database
REVOKE ALL PRIVILEGES ON DATABASE DEVELOPMENT FROM ROLE airflow_role_dev;
REVOKE ALL PRIVILEGES ON DATABASE DEVELOPMENT FROM ROLE dbt_role_dev;
REVOKE ALL PRIVILEGES ON DATABASE DEVELOPMENT FROM ROLE metabase_role_dev;

-- Step 2: Revoke all privileges from PUBLIC just in case
REVOKE ALL PRIVILEGES ON DATABASE DEVELOPMENT FROM ROLE PUBLIC;

-- Step 3: Grant database usage
GRANT USAGE ON DATABASE DEVELOPMENT TO ROLE airflow_role_dev;
GRANT USAGE ON DATABASE DEVELOPMENT TO ROLE dbt_role_dev;
GRANT USAGE ON DATABASE DEVELOPMENT TO ROLE metabase_role_dev;

-- Step 4: Schema-level grants per schema

-- TEST_SCHEMA
GRANT USAGE ON SCHEMA DEVELOPMENT.TEST_SCHEMA TO ROLE airflow_role_dev;
GRANT USAGE ON SCHEMA DEVELOPMENT.TEST_SCHEMA TO ROLE dbt_role_dev;
GRANT USAGE ON SCHEMA DEVELOPMENT.TEST_SCHEMA TO ROLE metabase_role_dev;

GRANT SELECT ON ALL TABLES IN SCHEMA DEVELOPMENT.TEST_SCHEMA TO ROLE metabase_role_dev;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DEVELOPMENT.TEST_SCHEMA TO ROLE airflow_role_dev;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DEVELOPMENT.TEST_SCHEMA TO ROLE dbt_role_dev;

-- DIM
GRANT USAGE ON SCHEMA DEVELOPMENT.DIM TO ROLE airflow_role_dev;
GRANT USAGE ON SCHEMA DEVELOPMENT.DIM TO ROLE dbt_role_dev;
GRANT USAGE ON SCHEMA DEVELOPMENT.DIM TO ROLE metabase_role_dev;

GRANT SELECT ON ALL TABLES IN SCHEMA DEVELOPMENT.DIM TO ROLE metabase_role_dev;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DEVELOPMENT.DIM TO ROLE airflow_role_dev;

-- FACT
GRANT USAGE ON SCHEMA DEVELOPMENT.FACT TO ROLE airflow_role_dev;
GRANT USAGE ON SCHEMA DEVELOPMENT.FACT TO ROLE dbt_role_dev;
GRANT USAGE ON SCHEMA DEVELOPMENT.FACT TO ROLE metabase_role_dev;

GRANT SELECT ON ALL TABLES IN SCHEMA DEVELOPMENT.FACT TO ROLE metabase_role_dev;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DEVELOPMENT.FACT TO ROLE airflow_role_dev;

-- SOURCE
GRANT USAGE ON SCHEMA DEVELOPMENT.SOURCE TO ROLE airflow_role_dev;
GRANT USAGE ON SCHEMA DEVELOPMENT.SOURCE TO ROLE dbt_role_dev;
GRANT USAGE ON SCHEMA DEVELOPMENT.SOURCE TO ROLE metabase_role_dev;

GRANT SELECT ON ALL TABLES IN SCHEMA DEVELOPMENT.SOURCE TO ROLE metabase_role_dev;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DEVELOPMENT.SOURCE TO ROLE airflow_role_dev;

-- EXPERIMENTAL
GRANT USAGE ON SCHEMA DEVELOPMENT.EXPERIMENTAL TO ROLE airflow_role_dev;
GRANT USAGE ON SCHEMA DEVELOPMENT.EXPERIMENTAL TO ROLE dbt_role_dev;
GRANT USAGE ON SCHEMA DEVELOPMENT.EXPERIMENTAL TO ROLE metabase_role_dev;

GRANT SELECT ON ALL TABLES IN SCHEMA DEVELOPMENT.EXPERIMENTAL TO ROLE metabase_role_dev;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DEVELOPMENT.EXPERIMENTAL TO ROLE airflow_role_dev;

-- MARTS
GRANT USAGE ON SCHEMA DEVELOPMENT.MARTS TO ROLE airflow_role_dev;
GRANT USAGE ON SCHEMA DEVELOPMENT.MARTS TO ROLE dbt_role_dev;
GRANT USAGE ON SCHEMA DEVELOPMENT.MARTS TO ROLE metabase_role_dev;

GRANT SELECT ON ALL TABLES IN SCHEMA DEVELOPMENT.MARTS TO ROLE metabase_role_dev;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DEVELOPMENT.MARTS TO ROLE airflow_role_dev;

-- STAGING
GRANT USAGE ON SCHEMA DEVELOPMENT.STAGING TO ROLE airflow_role_dev;
GRANT USAGE ON SCHEMA DEVELOPMENT.STAGING TO ROLE dbt_role_dev;
GRANT USAGE ON SCHEMA DEVELOPMENT.STAGING TO ROLE metabase_role_dev;

-- STAGING only had admin via airflow in prod, no write roles
-- No table grants needed unless you want to allow reading/writing
