name: Astronomer Deployment

on:
  push:
    branches:
      - master

env:
  ## Sets API token as an environment variable
  ASTRONOMER_KEY_ID: ${{ secrets.ASTRO_KEY }}
  ASTRONOMER_KEY_SECRET: ${{ secrets.ASTRO_SECRET_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: Install Astro CLI
      run: |
        curl -sSL install.astronomer.io | sudo bash -s

    - name: Deploy to Astro
      run: |
        astro deploy