name: Tests

on:
  pull_request:

jobs:
  pytest_build:
    name: Pytest 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Astro CLI
        run: |
          curl -sSL install.astronomer.io | sudo bash -s
      - name: Run Test Suite
        run: |
          astro dev pytest